services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/mydatabase

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8008:80
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD= password

volumes:
  db_data:
